const STORAGE_KEY="ccc_v42_checkins";
const EXERCISE_META={
 "Incline DB Press":{icon:"💪",cue:"30–45° bench, press to upper chest."},
 "Flat DB Press":{icon:"🏋️",cue:"Feet planted, steady press."},
 "Cable Fly":{icon:"🪽",cue:"Soft bend in elbows, squeeze chest."},
 "Rope Pushdown":{icon:"🔽",cue:"Pin elbows in, full extension."},
 "DB Curl":{icon:"💥",cue:"Keep elbows quiet, control down."},
 "Hammer Curl":{icon:"🔨",cue:"Neutral grip, slow lower."},
 "Chest Supported Row":{icon:"🚣",cue:"Chest down, squeeze shoulder blades."},
 "Lat Pulldown":{icon:"⬇️",cue:"Pull to upper chest, avoid swinging."},
 "Seated Cable Row":{icon:"↩️",cue:"Tall chest, pull elbows back."},
 "Face Pull":{icon:"🎯",cue:"Pull high, rotate thumbs back."},
 "Bird Dog":{icon:"🧠",cue:"Brace core, move slow."},
 "McGill Curl-Up":{icon:"🛡️",cue:"Lift slightly, no spinal crunch."},
 "Plank":{icon:"📏",cue:"Straight line, brace abs."},
 "Leg Press":{icon:"🦵",cue:"Pain-free depth only."},
 "DB Romanian Deadlift":{icon:"⚙️",cue:"Hinge hips, neutral spine."},
 "Low Step-Ups":{icon:"📶",cue:"Low box, drive through heel."},
 "Hamstring Curl":{icon:"🧩",cue:"Control up and down."},
 "Calf Raise":{icon:"⬆️",cue:"Pause at top."},
 "Side Plank":{icon:"📐",cue:"Stack shoulders and hips."},
 "Seated DB Shoulder Press":{icon:"🏛️",cue:"Stay tall, avoid back arch."},
 "Lateral Raise":{icon:"✈️",cue:"Lift to side, not shrug."},
 "Rear Delt Fly":{icon:"🪽",cue:"Open wide, squeeze rear delt."},
 "Farmer Carry":{icon:"🧳",cue:"Tall posture, slow steps."},
 "Pushups burnout":{icon:"🔥",cue:"Brace core, full-body plank."},
 "Curl burnout":{icon:"🔥",cue:"Controlled reps, no swinging."},
 "Glute Bridge":{icon:"🌉",cue:"Drive hips up, squeeze glutes."},
 "Bodyweight box squat":{icon:"📦",cue:"Sit back to box, stand tall."},
 "Goblet Squat":{icon:"🏺",cue:"Hold weight high, pain-free depth."},
 "Treadmill incline walk":{icon:"🚶",cue:"Steady pace, chest up."},
 "Brisk walk":{icon:"🚶",cue:"Fast pace, relaxed shoulders."}
};
const EXERCISE_LINKS={};
Object.keys(EXERCISE_META).forEach(name=>EXERCISE_LINKS[name]=`https://www.youtube.com/results?search_query=${encodeURIComponent(name+" proper form")}`);
const workouts={home:[{name:"Day 1 — Chest + Arms",focus:"Upper chest, triceps, biceps",duration:"55 min",plan:["Incline DB Press 4x10","Flat DB Press 3x10","Cable Fly 3x15","Rope Pushdown 4x12","DB Curl 4x12","Hammer Curl 3x15"]},{name:"Day 2 — Back + Core",focus:"Back strength, posture, spine stability",duration:"50 min",plan:["Chest Supported Row 4x10","Lat Pulldown 4x12","Seated Cable Row 3x12","Face Pull 3x15","Bird Dog 3 rounds","McGill Curl-Up 3 rounds","Plank 3x30 sec"]},{name:"Day 3 — Legs Safe Mode",focus:"Knee-friendly lower body",duration:"45 min",plan:["Leg Press 4x12","DB Romanian Deadlift 4x10","Low Step-Ups 3x10","Hamstring Curl 3x15","Calf Raise 4x15","Side Plank 3 rounds"]},{name:"Day 4 — Wayne Armor",focus:"Shoulders, carries, presence",duration:"50 min",plan:["Seated DB Shoulder Press 4x10","Lateral Raise 4x15","Rear Delt Fly 4x15","Farmer Carry 5 rounds","Pushups burnout","Curl burnout"]}],travel:{hotel:{name:"Hotel Gym Express",focus:"Fast full body",duration:"30 min",plan:["Flat DB Press 3x12","Goblet Squat 3x12","Chest Supported Row 3x12","Seated DB Shoulder Press 3x10","Treadmill incline walk 10 min"]},bodyweight:{name:"No Equipment Reset",focus:"Mobility + sweat",duration:"20 min",plan:["Pushups burnout","Bodyweight box squat 3x12","Bird Dog 3x10","McGill Curl-Up 3x10","Brisk walk 10 min"]},recovery:{name:"Back-Safe Travel Day",focus:"Recovery",duration:"15 min",plan:["Bird Dog x10","McGill Curl-Up x10","Glute Bridge x15","Brisk walk 10 min"]}}};
const formLibrary=[{exercise:"Incline DB Press",cue:"Bench at 30–45°. Lower to upper chest, elbows about 45°, press without bouncing."},{exercise:"Chest Supported Row",cue:"Keep chest planted. Pull elbows back and squeeze shoulder blades at the top."},{exercise:"DB Romanian Deadlift",cue:"Soft knees, hinge at hips, keep dumbbells close, stop before low back rounds."},{exercise:"Leg Press",cue:"Use pain-free depth. Control the lowering phase. Do not let hips roll off the pad."},{exercise:"Farmer Carry",cue:"Stand tall, ribs down, brace abs, walk slow and controlled."},{exercise:"McGill Curl-Up",cue:"One knee bent, hands under low back, brace core and lift shoulders slightly."}];
const $=id=>document.getElementById(id);
const els={tabs:document.querySelectorAll(".tab"),panels:document.querySelectorAll(".tab-panel"),trainList:$("trainList"),formList:$("formList"),travelList:$("travelList"),travelSelect:$("travelSelect"),readinessPill:$("readinessPill"),readinessBar:$("readinessBar"),coachMessage:$("coachMessage"),statWeight:$("statWeight"),statWaist:$("statWaist"),statProtein:$("statProtein"),statSteps:$("statSteps"),sumEntries:$("sumEntries"),sumProtein:$("sumProtein"),sumSteps:$("sumSteps"),sumEnergy:$("sumEnergy"),entryCountFooter:$("entryCountFooter"),miniChart:$("miniChart"),historyChart:$("historyChart"),entryList:$("entryList"),saveBtn:$("saveBtn"),clearFormBtn:$("clearFormBtn"),exportBtn:$("exportBtn"),deleteAllBtn:$("deleteAllBtn"),saveStatus:$("saveStatus"),date:$("date"),weight:$("weight"),waist:$("waist"),protein:$("protein"),steps:$("steps"),backPain:$("backPain"),kneePain:$("kneePain"),energy:$("energy"),notes:$("notes")};
function getData(){return JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]")}
function setData(data){localStorage.setItem(STORAGE_KEY,JSON.stringify(data))}
function todayISO(){return new Date().toISOString().slice(0,10)}
function calculateReadiness(entry){if(!entry)return 0;const protein=Math.min(Number(entry.protein||0)/190,1)*25;const steps=Math.min(Number(entry.steps||0)/8000,1)*20;const energy=(Math.min(Number(entry.energy||0),10)/10)*20;const back=((10-Math.min(Number(entry.backPain||0),10))/10)*17.5;const knee=((10-Math.min(Number(entry.kneePain||0),10))/10)*17.5;return Math.round(protein+steps+energy+back+knee)}
function getCoachMessage(entry,readiness){if(!entry)return"Start by saving your first check-in.";const back=Number(entry.backPain||0),knee=Number(entry.kneePain||0);if(back>=6)return"Back is flaring up. Use Back-Safe Travel Day or rehab only. Skip heavy hinges today.";if(knee>=6)return"Knee is talking. Replace step-ups with curls, lighter leg press, and extra walking.";if(readiness>=80)return"Green light. Push the main lift hard today and finish with carries or incline walking.";if(readiness>=65)return"Solid day. Hit the full session, but leave 1–2 reps in reserve on each set.";return"Recovery emphasis. Do the warm-up, shorter lift, and focus on protein, water, and steps."}
function baseExercise(label){return label.replace(/\s+\d+x\d+$/,'').replace(/\s+x\d+$/,'')}
function linkForExercise(label){const clean=baseExercise(label);return EXERCISE_LINKS[clean]||`https://www.youtube.com/results?search_query=${encodeURIComponent(clean+" proper form")}`}
function metaForExercise(label){const clean=baseExercise(label);return EXERCISE_META[clean]||{icon:"🎬",cue:"See example link for form."}}
function workoutCard(item){const hero=baseExercise(item.plan[0]);const meta=metaForExercise(hero);const steps=item.plan.map(step=>`<div class="plan-step">${step}</div>`).join("");const links=item.plan.slice(0,4).map(step=>{const clean=baseExercise(step);return `<a class="example-link" target="_blank" rel="noopener noreferrer" href="${linkForExercise(step)}">▶ ${clean}</a>`}).join("");return `<div class="workout-card"><div class="workout-media"><div class="thumb">${meta.icon}</div><div><div class="workout-top"><div><div class="mission-title">${item.name}</div><div class="muted">${item.focus}</div></div><div class="badge">${item.duration}</div></div><div class="field-help">${meta.cue}</div></div></div>${steps}<div class="link-row"><a class="example-link primary" target="_blank" rel="noopener noreferrer" href="${linkForExercise(hero)}">▶ Watch Main Exercise</a>${links}</div><button class="btn btn-gold" type="button" style="margin-top:12px;">Start Session</button></div>`}
function renderTrain(){els.trainList.innerHTML=workouts.home.map(workoutCard).join("");els.formList.innerHTML=formLibrary.map(item=>{const meta=metaForExercise(item.exercise);return `<div class="form-cue"><div class="workout-media"><div class="thumb">${meta.icon}</div><div><strong>${item.exercise}</strong>${item.cue}</div></div><div class="link-row"><a class="example-link primary" target="_blank" rel="noopener noreferrer" href="${linkForExercise(item.exercise)}">▶ Watch Example</a></div></div>`}).join("")}
function renderTravel(mode){els.travelList.innerHTML=workoutCard(workouts.travel[mode])}
function activateTab(name){els.tabs.forEach(tab=>tab.classList.toggle("active",tab.dataset.tab===name));els.panels.forEach(panel=>panel.classList.toggle("active",panel.id===name))}
function avg(arr,key){const vals=arr.map(x=>Number(x[key]||0)).filter(v=>!Number.isNaN(v)&&v>0);if(!vals.length)return 0;return Math.round((vals.reduce((a,b)=>a+b,0)/vals.length)*10)/10}
function latestEntry(data){if(!data.length)return null;return [...data].sort((a,b)=>(b.date||"").localeCompare(a.date||""))[0]}
function updateSummary(data){const last30=[...data].sort((a,b)=>(a.date||"").localeCompare(b.date||"")).slice(-30);els.sumEntries.textContent=data.length;els.sumProtein.textContent=avg(last30,"protein");els.sumSteps.textContent=Math.round(avg(last30,"steps"));els.sumEnergy.textContent=avg(last30,"energy");els.entryCountFooter.textContent=`${data.length} Entr${data.length===1?"y":"ies"}`}
function updateHome(data){const entry=latestEntry(data),readiness=calculateReadiness(entry);els.readinessPill.textContent=`${readiness}%`;els.readinessBar.style.width=`${readiness}%`;els.coachMessage.textContent=getCoachMessage(entry,readiness);els.statWeight.textContent=entry?.weight?`${entry.weight} lb`:"--";els.statWaist.textContent=entry?.waist?`${entry.waist} in`:"--";els.statProtein.textContent=entry?.protein?`${entry.protein} g`:"--";els.statSteps.textContent=entry?.steps?`${entry.steps}`:"--"}
function drawLineChart(canvas,data,key,color){const ctx=canvas.getContext("2d");const width=canvas.clientWidth,height=canvas.clientHeight;canvas.width=width*devicePixelRatio;canvas.height=height*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);ctx.clearRect(0,0,width,height);ctx.fillStyle="rgba(255,255,255,0.02)";ctx.fillRect(0,0,width,height);const sorted=[...data].sort((a,b)=>(a.date||"").localeCompare(b.date||"")).slice(-10);const vals=sorted.map(d=>Number(d[key]||0)).filter(v=>!Number.isNaN(v)&&v>0);if(!vals.length){ctx.fillStyle="#94a3b8";ctx.font="14px -apple-system, sans-serif";ctx.fillText("No data yet",16,28);return}const min=Math.min(...vals),max=Math.max(...vals),range=Math.max(max-min,1);ctx.strokeStyle="rgba(255,255,255,0.08)";ctx.lineWidth=1;for(let i=0;i<4;i++){const y=20+(height-40)*(i/3);ctx.beginPath();ctx.moveTo(10,y);ctx.lineTo(width-10,y);ctx.stroke()}ctx.strokeStyle=color;ctx.lineWidth=3;ctx.beginPath();sorted.forEach((d,i)=>{const v=Number(d[key]||0);const x=16+((width-32)*(sorted.length===1?0.5:i/(sorted.length-1)));const y=height-18-(((v-min)/range)*(height-40));if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)});ctx.stroke();ctx.fillStyle="#f8fafc";ctx.font="12px -apple-system, sans-serif";ctx.fillText(`Latest ${key}: ${sorted[sorted.length-1][key]||"--"}`,16,16)}
function renderHistory(data){const sorted=[...data].sort((a,b)=>(b.date||"").localeCompare(a.date||""));if(!sorted.length){els.entryList.innerHTML='<div class="rule">No entries saved yet. Use Track to add your first check-in.</div>';return}els.entryList.innerHTML=sorted.map((entry,idx)=>{const readiness=calculateReadiness(entry);return `<div class="entry-item"><div class="entry-top"><div><div class="mission-title">${entry.date||"No date"}</div><div class="muted">Readiness ${readiness}%</div></div></div><div class="entry-meta"><div class="meta-chip">Weight: ${entry.weight||"--"} lb</div><div class="meta-chip">Waist: ${entry.waist||"--"} in</div><div class="meta-chip">Protein: ${entry.protein||"--"} g</div><div class="meta-chip">Steps: ${entry.steps||"--"}</div><div class="meta-chip">Back: ${entry.backPain||"--"}/10</div><div class="meta-chip">Knee: ${entry.kneePain||"--"}/10</div><div class="meta-chip">Energy: ${entry.energy||"--"}/10</div></div>${entry.notes?`<div class="entry-note">${entry.notes}</div>`:""}<div class="entry-actions"><button class="delete-btn" type="button" data-index="${idx}">Delete</button></div></div>`}).join("");document.querySelectorAll(".delete-btn").forEach(btn=>btn.addEventListener("click",()=>deleteEntry(btn.dataset.index)))}
function deleteEntry(sortedIndex){const data=getData();const sorted=[...data].sort((a,b)=>(b.date||"").localeCompare(a.date||""));const target=sorted[sortedIndex];let removed=false;const next=data.filter(item=>{if(!removed&&item.date===target.date&&item.weight==target.weight&&item.steps==target.steps&&item.protein==target.protein&&item.notes==target.notes){removed=true;return false}return true});setData(next);refreshAll()}
function exportData(){const data=getData();const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="ccc_v42_checkins.json";a.click();URL.revokeObjectURL(url)}
function clearForm(){els.date.value=todayISO();["weight","waist","protein","steps","backPain","kneePain","energy","notes"].forEach(id=>els[id].value="");els.saveStatus.textContent=""}
function saveCheckIn(){const entry={date:els.date.value||todayISO(),weight:els.weight.value,waist:els.waist.value,protein:els.protein.value,steps:els.steps.value,backPain:els.backPain.value,kneePain:els.kneePain.value,energy:els.energy.value,notes:els.notes.value};const data=getData();data.push(entry);setData(data);els.saveStatus.textContent=`Saved ${entry.date} on this device at ${new Date().toLocaleTimeString([], {hour:'numeric', minute:'2-digit'})}.`;refreshAll()}
function refreshAll(){const data=getData();updateHome(data);updateSummary(data);renderHistory(data);drawLineChart(els.miniChart,data,"weight","#f59e0b");drawLineChart(els.historyChart,data,"weight","#34d399")}
els.tabs.forEach(tab=>tab.addEventListener("click",()=>activateTab(tab.dataset.tab)));els.travelSelect.addEventListener("change",e=>renderTravel(e.target.value));els.saveBtn.addEventListener("click",saveCheckIn);els.clearFormBtn.addEventListener("click",clearForm);els.exportBtn.addEventListener("click",exportData);els.deleteAllBtn.addEventListener("click",()=>{if(confirm("Delete all saved entries on this device?")){setData([]);refreshAll()}});document.querySelectorAll(".chip").forEach(btn=>btn.addEventListener("click",()=>{const target=$(btn.dataset.fill);if(target){target.value=btn.dataset.value}}));
els.date.value=todayISO();renderTrain();renderTravel("hotel");refreshAll();
